CREATE TABLE Homework(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT
);

CREATE TABLE Lesson(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	homework_id INT REFERENCES Homework(id) ON DELETE CASCADE
);

CREATE TABLE Schedule (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Schedule_Lesson (
    schedule_id INT REFERENCES Schedule(id) ON DELETE CASCADE,
    lesson_id INT REFERENCES Lesson(id) ON DELETE CASCADE,
    PRIMARY KEY (schedule_id, lesson_id)
);

